### ISSUE TITLE
Remove From System

### ISSUE THREAD

**Issue by hall0wedccs** [Hawkish-Eyes/Hawkish-Eyes#1]
I was testing out Hawkish eyes on myself with a webhook to a private server with just me in it, every time i boot up/log into discord, hawkish eyes sends more info to that webhook so it must still be running on my system, how do i get rid of it?

**Comment by Hawkishx** [comment]
sorry to hear that, hawkish is certainly in your startup windows, it injects itself into your chrome browsers and into your discord client I'm going to do a simple script on my github to remove it don't worry, but it's really difficult to remove

**Comment by Hawkishx** [comment]
lmao I went a little hard on the injections

**Comment by hall0wedccs** [comment]
I checked my startup and don't see any hawkish-eyes stuff, would the name be disguised?

**Comment by hall0wedccs** [comment]
Oh wait I wasn't logged out nor was a message sent to my webhook so i think you removed it, thank you very much!
