### ISSUE TITLE
Malware on top of malware

### ISSUE THREAD

**Issue by Pasha-malware** [Hawkish-Eyes/Hawkish-Eyes#7]
Dont touch this shit
https://github.com/Hawkish-Eyes/Hawkish-Eyes/blob/main/main.py#L102
https://github.com/Hawkish-Eyes/Hawkish-Inject/blob/main/index.js#L24

**Comment by Pasha-malware** [comment]
If u delete this I will make a new issue and so on, dont even try retards

**Comment by Pasha-malware** [comment]
Its also skidded and dualhooked

**Comment by Hawkishx** [comment]
i'm the owner of sordeal/blackcap so...
i'm not a skid and https://github.com/Hawkish-Eyes/Hawkish-Eyes/blob/main/README.md#L253 
also if you re create an issue i will just block your account

**Comment by Pasha-malware** [comment]
just stop dualhooking ur stuff not funny man
